usrloc - fix column types not initialized on update
some columns were not initialized on update leading to errors in update

ERROR: db_text [dbt_lib.c:464]: dbt_is_neq_type(): invalid datatype -1001432832
ERROR: db_text [dbt_base.c:560]: dbt_update(): incompatible types!
ERROR: db_text [dbt_base.c:599]: dbt_update(): failed to update the table!
(cherry picked from commit cf521e66825fea4b7498d615d435739628fe4c09)